apiVersion: v1
kind: Pod
metadata:
  name: multicast-transmitter
  labels:
    app: multicast-test
    role: transmitter
spec:
  containers:
  - name: transmitter
    image: ghcr.io/niranec77/multicast-transmitter:latest
    imagePullPolicy: Always
    env:
    - name: MULTICAST_ADDR
      value: "224.0.1.105"
    - name: MULTICAST_PORT
      value: "45688"
    - name: INTERVAL
      value: "2"
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
---
# ConfigMap with transmitter test scripts
apiVersion: v1
kind: ConfigMap
metadata:
  name: multicast-transmitter-scripts
data:
  send-jboss-heartbeat.sh: |
    #!/bin/bash
    # Simulates JBoss JGroups cluster heartbeat
    MULTICAST_ADDR="${MULTICAST_ADDR:-224.0.1.105}"
    MULTICAST_PORT="${MULTICAST_PORT:-45688}"
    INTERVAL="${INTERVAL:-2}"
    
    echo "Starting JBoss-style multicast transmitter..."
    echo "Address: $MULTICAST_ADDR:$MULTICAST_PORT"
    echo "Interval: ${INTERVAL}s"
    echo ""
    
    count=0
    while true; do
      count=$((count + 1))
      message="JBOSS_HEARTBEAT|node=transmitter-pod|seq=$count|time=$(date -Iseconds)"
      echo "Sending: $message"
      echo "$message" | socat - UDP4-DATAGRAM:${MULTICAST_ADDR}:${MULTICAST_PORT},so-broadcast
      sleep $INTERVAL
    done
  
  send-single.sh: |
    #!/bin/bash
    # Send a single multicast message
    MULTICAST_ADDR="${1:-224.0.1.105}"
    MULTICAST_PORT="${2:-45688}"
    MESSAGE="${3:-Test multicast message from JBoss transmitter}"
    
    echo "Sending to $MULTICAST_ADDR:$MULTICAST_PORT"
    echo "Message: $MESSAGE"
    echo "$MESSAGE" | socat - UDP4-DATAGRAM:${MULTICAST_ADDR}:${MULTICAST_PORT},so-broadcast
    echo "Done."

